### ISSUE TITLE
Commonjs support

### ISSUE THREAD

**Issue by baspete** [robdodson/angular-custom-elements#2]
How about making this importable as an es6/commonjs module, so we can bring it in using npm or jspm?

**Comment by robdodson** [comment]
Good call! Yeah I can do that :)

**Comment by robdodson** [comment]
I added a UMD wrapper in #7 to help with this, so you should now be able to `require` it at least. I need to spend a bit more time to sort out how to gracefully distribute ES2015 to Commonjs to regular script tag. If you have any examples of ES2015 directives I'd love to take a look at them just to grok what is the preferred Angular 1.x way of doing things
