### ISSUE TITLE
one-way bindings current only work in Chrome (Polymer bug)

### ISSUE THREAD

**Issue by robdodson** [robdodson/angular-custom-elements#3]
If you give Polymer both an attribute AND a property it looks like it uses the attribute when the element finally boots up.

Looks like this'll be fixed in the next release of Polymer Polymer/polymer#3779

**Comment by robdodson** [comment]
Note, this only affects the one-way bindings. The interpolated binding directive works fine in other browsers because it doesn't directly set a property

**Comment by Splaktar** [comment]
It looks like this was merged on July 22nd (https://github.com/Polymer/polymer/pull/3780). Does that mean that it was part of Polymer 1.7.0?

**Comment by robdodson** [comment]
yep it looks like it should be in 1.7
